version: '3.8'

services:
  mqtt-wol:
    # Use pre-built image from GitHub Container Registry
    # To build locally instead, uncomment the 'build: .' line and comment out the 'image' line
    image: ghcr.io/bradmatt275/wake-from-mqtt:latest
    # build: .
    container_name: mqtt-wol-service
    restart: unless-stopped
    network_mode: host  # Required for WOL packets to work properly
    environment:
      # MQTT Configuration (required)
      - MQTT_BROKER=${MQTT_BROKER}  # Required: your MQTT broker IP
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME}  # Optional
      - MQTT_PASSWORD=${MQTT_PASSWORD}  # Optional
      - MQTT_TOPIC=${MQTT_TOPIC:-home/wake}
      - MQTT_USE_TLS=${MQTT_USE_TLS:-false}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    
    # Optional: Mount logs directory for persistent logging
    # volumes:
    #   - ./logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s