name: Bug Report
description: Report a bug or issue with the MQTT Wake-on-LAN service
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - Docker version
        - Operating system
        - Network setup (VLANs, etc.)
        - MQTT broker details
      placeholder: |
        Docker version: 
        OS: 
        Network setup: 
        MQTT broker: 
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your docker-compose.yml and .env file (remove sensitive information like passwords)
      render: yaml